package com.thhreadnames;

import com.creation.MyThread;

public class ThreadNameDemo {
    public static void main(String[] args) {

        String threadNames = """
                -> Every Thread in java has some name it may be provided explicitly by the
                programmer or automatically generated by JVM.
                -> Thread class defines the following methods to get and set name of a Thread.
                """;

        System.out.println(threadNames);

        System.out.println(Thread.currentThread().getName());
        MyThread t =new MyThread();
        System.out.println(t.getName());
        Thread.currentThread().setName("Dileep");
        System.out.println(Thread.currentThread().getName());
    }
}
